### PR TITLE
Conversion help files

### PR DESCRIPTION
**Pull request by MattS6464**
updated help files and added musical example to valconvert.

### CODE REVIEW

**Comment by AlexHarker** [comment]
Looks great. Could you just change the signal description in the xml for valconvert~

"When valconvert~  receives a value, that value is scaled, based on the chosen mode, to the indicated output range of values and ouput as a signal."

so it starts something like "When valconvert~ receives an input signal" or "valconvert~ scales its input signal...."?

**Comment by MattS6464** [comment]
Reworded the unclear part of the valconvert~ xml

**Comment by AlexHarker** [comment]
Thanks - wasn't the grammar - just sounded like the input was a message - all good now!

**Comment by AlexHarker** [comment]
Rename "message" to "anything" in the reference to match Max style

**Pull request merged**
