### PR TITLE
Utility help files

### PR DESCRIPTION
**Pull request by MattS6464**
Tidied and updated Utility help files and added the arguments jsui object where necessary.

### CODE REVIEW

**Comment by AlexHarker** [comment]
There are a couple of errors in the xml for recursivefolder. The message for changing type(s) is "types" and not "type".

Also the "file-path" message is listed, but in reality you just send any symbol or any message starting with a symbol with the path (for some reason I've implemented both, although I'd assume that just listing the symbol would be fine).

**Comment by AlexHarker** [comment]
macaddress has an optional symbol argument to set the interface type (can be "any" "wifi" ""ethernet" or the name of a network type). There's also a "set" message that allows you to set that. Sorry - I seemed to have missed that last year.

**Comment by AlexHarker** [comment]
Otherwise this looks good - let me know when the items above are resolved and I'll review again.

**Comment by MattS6464** [comment]
Added the missing messages/args and corrected the issues. Also updated the macaddress help to show the previously missed features

**Comment by AlexHarker** [comment]
Cool - could you do a couple of things with macaddress before I merge?

1 - space the refs nicely over lines with options (like for the types message for recursivefolder, but for the any/wifi lines etc.)

Totally my fault but I should have said rather than "name of a network type" something more precise like "a network interface name (e.g. en0)" - could you update the relevant places to that and maybe add en0 as an example (it'll likely match one of the other networks).

**Comment by MattS6464** [comment]
Made the network interface part clearer, added en0 as an example in help file and xml, made nicer spacing in the xml

**Comment by AlexHarker** [comment]
Great! Thanks

**Comment by AlexHarker** [comment]
Just checking here re the previous issue on sample accurate objects, and for depack in the reference "input" should be "message" or "list" (or doubled as both) - if you left click the object you'll get a list of messages which should be explained in the reference - for this object it's anything (message) / list / int / float so that's probably what should be covered if we want to match Max (subject to discussion).

recursivefolder also has a slightly different list of items (including int which isn't covered in the refs - for some reason this just calls the bang function)

**Comment by AlexHarker** [comment]
Actually "message" is usually named as "anything" in max as per the drop down when left right-clicking

**Pull request merged**
